### PR TITLE
Increase gas consumption, add note on it's value

### PR DESCRIPTION
**Pull request by EmelyanenkoK**

### CODE REVIEW

**Review by Meroksa — APPROVED** [review]

**Comment by cumcum8197** [comment]
f2253cb0f0e1ae0974d7dc0cef3a62cb6e19f806

**Comment by cumcum8197** [comment]
b33ed39c79ef9d1e27535bb2407b24ae4774f00c

**Comment by cumcum8197** [comment]
733f3793012405267202c9c245a9d87fda37f5f4

**Comment by cumcum8197** [comment]
733f3793012405267202c9c245a9d87fda37f5f4

**Pull request merged**
